# config/meta.yml
meta_title: "Alexandre Cordani- Agent Immobilier - Opportunity Manager - Photographe immobilier - Developper Web Junior.""
meta_description: "Visitez mon site personnel. Agent Immobilier - Opportunity Manager - Photographe immobilier - Developper Web Junior."
meta_image: ".jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@" # indispensable pour les Twitter Cards